#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

# Editor
export EDITOR='vim'
export VISUAL='vim'

# Remove duplicates
typeset -gU PATH path
path=($HOME/bin(N-/) $path)

# Set Format for time command
TIMEFMT='  real %*E  user %*U  kernel %*S  %J'

