#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
# Source my aliases
if [[ -e "$HOME/.zsh_aliases" ]]; then
  source "$HOME/.zsh_aliases"
fi

setopt no_beep

# Set LS_COLORS
eval $(dircolors | sed 's/ow=..;../ow=01;35/')

